Repository apache/skywalking-swck, pull requests merged in 2020-11, with the labels that each got.

#6 Add branch protection and requires checks/reviews before merging
  .asf.yaml
Labels: chore

#7 Give a explicit check context
  .github/workflows/go.yml
Labels: chore

#5 Update README.md
  .gitignore
  CHANGES.md
  Dockerfile
  Makefile
  PROJECT
  README.md
  build/package/release.sh
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/oapserver_controller.go
  golangci.yml
Labels: documentation

#8 Tweak release scripts and polish the release doc
  CONTRIBUTING.md
  Makefile
  build/package/release.sh
  doc/release.md
Labels: chore, documentation

#9 Fix typo in binary name
  Makefile
Labels: chore

#10 Update release.md
  doc/release.md
Labels: documentation

#11 Fix copy-paste typo
  doc/release.md
Labels: documentation

#12 Introduce custom metrics apiserver which is an adapter to OAP cluster
  .gitignore
  CHANGES.md
  Makefile
  PROJECT
  README.md
  apis/operator/v1alpha1/groupversion_info.go
  apis/operator/v1alpha1/oapserver_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  build/images/Dockerfile.adapter
  build/images/Dockerfile.operator
  cmd/adapter/adapter.go
  cmd/build/main.go
  cmd/manager/manager.go
  config/adapter/apiserver_auth_reader_role_binding.yaml
  config/adapter/kustomization.yaml
  config/adapter/namespaced/adapter/adapter.yaml
  config/adapter/namespaced/adapter/kustomization.yaml
  config/adapter/namespaced/apiservice/custom.yaml
  config/adapter/namespaced/apiservice/external.yaml
  config/adapter/namespaced/apiservice/kustomization.yaml
  config/adapter/namespaced/kustomization.yaml
  config/adapter/namespaced/rbac/apiserver_auth_delegator_cluster_role_binding.yaml
  config/adapter/namespaced/rbac/apiserver_resource_reader_cluster_role_binding.yaml.yaml
  config/adapter/namespaced/rbac/custom_metrics_cluster_role.yaml
  config/adapter/namespaced/rbac/custom_metrics_resource_reader_cluster_role.yaml
  config/adapter/namespaced/rbac/hpa_custom_metrics_cluster_role_binding.yaml
  config/adapter/namespaced/rbac/kustomization.yaml
  config/dev/adapter/adapter.yaml
  config/dev/adapter/kustomization.yaml
  config/operator/crd/bases/operator.skywalking.apache.org_oapservers.yaml
  config/operator/crd/kustomization.yaml
  config/operator/crd/kustomizeconfig.yaml
  config/operator/crd/patches/cainjection_in_oapservers.yaml
  config/operator/crd/patches/webhook_in_oapservers.yaml
  config/operator/default/kustomization.yaml
  config/operator/default/manager_auth_proxy_patch.yaml
  config/operator/manager/kustomization.yaml
  config/operator/manager/manager.yaml
  config/operator/rbac/auth_proxy_client_clusterrole.yaml
  config/operator/rbac/auth_proxy_role.yaml
  config/operator/rbac/auth_proxy_role_binding.yaml
  config/operator/rbac/auth_proxy_service.yaml
  config/operator/rbac/kustomization.yaml
  config/operator/rbac/leader_election_role.yaml
  config/operator/rbac/leader_election_role_binding.yaml
  config/operator/rbac/role.yaml
  config/operator/rbac/role_binding.yaml
  config/operator/samples/oap.yaml
  controllers/operator/oapserver_controller.go
  doc/custom-metrics-adapter.md
  doc/operator.md
  go.mod
  go.sum
  pkg/provider/provider.go
  pkg/provider/registry.go
Labels: enhancement
