Repository apache/skywalking-swck, pull requests merged in 2021-11, with the labels that each got.

#42 Update menu.yml
  docs/menu.yml
Labels: chore

#43 Use https schema in documents
  CONTRIBUTING.md
  README.md
  docs/binary-readme.md
  docs/release.md
Labels: documentation

#44 Update release document
  docs/release.md
Labels: documentation

#48 fix bug
  controllers/operator/storage_controller.go
Labels: bug

#47 Remove deprecated Kubernetes API dependence
  Makefile
  apis/operator/v1alpha1/fetcher_webhook.go
  apis/operator/v1alpha1/javaagent_injector_webhook.go
  apis/operator/v1alpha1/javaagent_webhook.go
  apis/operator/v1alpha1/oapserver_webhook.go
  apis/operator/v1alpha1/storage_webhook.go
  apis/operator/v1alpha1/ui_webhook.go
  config/dev/operator/crd/bases/operator.skywalking.apache.org_fetchers.yaml
  config/dev/operator/crd/bases/operator.skywalking.apache.org_javaagents.yaml
  config/dev/operator/crd/bases/operator.skywalking.apache.org_oapservers.yaml
  config/dev/operator/crd/bases/operator.skywalking.apache.org_storages.yaml
  config/dev/operator/crd/bases/operator.skywalking.apache.org_uis.yaml
  config/operator/certmanager/certificate.yaml
  config/operator/crd/bases/operator.skywalking.apache.org_fetchers.yaml
  config/operator/crd/bases/operator.skywalking.apache.org_javaagents.yaml
  config/operator/crd/bases/operator.skywalking.apache.org_oapservers.yaml
  config/operator/crd/bases/operator.skywalking.apache.org_storages.yaml
  config/operator/crd/bases/operator.skywalking.apache.org_uis.yaml
  config/operator/crd/patches/cainjection_in_fetchers.yaml
  config/operator/crd/patches/cainjection_in_javaagents.yaml
  config/operator/crd/patches/cainjection_in_oapservers.yaml
  config/operator/crd/patches/cainjection_in_storages.yaml
  config/operator/crd/patches/cainjection_in_uis.yaml
  config/operator/crd/patches/webhook_in_fetchers.yaml
  config/operator/crd/patches/webhook_in_javaagents.yaml
  config/operator/crd/patches/webhook_in_oapservers.yaml
  config/operator/crd/patches/webhook_in_storages.yaml
  config/operator/crd/patches/webhook_in_uis.yaml
  config/operator/default/kustomization.yaml
  config/operator/default/webhookcainjection_patch.yaml
  config/operator/rbac/auth_proxy_client_clusterrole.yaml
  config/operator/webhook/manifests.yaml
  config/operator/webhook/ns_selector_patch.yaml
  controllers/operator/ui_controller.go
  controllers/operator/ui_controller_test.go
  hack/install-kubebuilder.sh
  pkg/operator/manifests/ui/templates/ingress.yaml
  pkg/operator/repo/assets.gen.go
Labels: enhancement
