Repository apache/skywalking-swck, pull requests merged in 2022-01, with the labels that each got.

#56 Fix the satellite config not support number error
  operator/pkg/operator/manifests/satellite/templates/deployment.yaml
  operator/pkg/operator/repo/assets.gen.go
Labels: bug

#57 Add stabilization windows feature in satellite HPA documentation
  docs/examples/satellite.md
  operator/config/samples/satellite-hpa.yaml
Labels: documentation

#55 Update change log and image tag for releasing 0.6.0
  CHANGES.md
  adapter/Makefile
  adapter/config/namespaced/adapter/kustomization.yaml
  docs/release.md
  hack/deploy.sh
  operator/Makefile
  operator/config/manager/kustomization.yaml
Labels: documentation

#59 Fix could not deploy metrics adapter to GKE
  CHANGES.md
  adapter/config/namespaced/adapter/adapter.yaml
Labels: bug

#60 Update image tag to 0.6.1
  adapter/config/namespaced/adapter/kustomization.yaml
  operator/config/manager/kustomization.yaml
Labels: chore

#61 [BUG]fix shell assignment
  hack/prepare-e2e.sh
Labels: testing

#62 Fix java-agent-injector usages link
  docs/java-agent-injector.md
Labels: chore
